apiVersion: v1
kind: Pod
metadata:
  labels:
    app: consul-app
  name: consul
spec:
  volumes:
    - name: consul-config-vol
      persistentVolumeClaim:
        claimName: consul-config-pvc
  containers:
  - image: consul:1.15.4
    name: consul
    volumeMounts:
      - mountPath: "/consul/config"
        name: consul-config-vol
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: consul-svc
  name: consul-svc
spec:
  ports:
  - name: "8500"
    nodePort: 30850
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul-app
  type: NodePort
