apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: consul-deploy
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consul-app
    spec:
      containers:
      - image: consul:1.15.4
        name: consul
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: consul-svc
  name: consul-svc
spec:
  ports:
  - name: "8500"
    nodePort: 30850
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul-app
  type: NodePort
